fail_fast: false

default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v4.4.0"
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: destroyed-symlinks
          - id: mixed-line-ending
          - id: check-json
          - id: check-yaml
    - repo: https://github.com/asottile/add-trailing-comma
      rev: "v3.0.0"
      hooks:
          - id: add-trailing-comma
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.0.277"
      hooks:
          - id: ruff
            always_run: true
